CustomHealthAPI.Enums.HealthTypes = {
	RED = 0,
	SOUL = 1,
	CONTAINER = 2,
	OVERLAY = 3,
	AFTER_HEALTH_ICON = 4,
	BELOW_HEALTH_ICON = 5,
}

-- Bitmask that defines what sort of health that can be overlayed by overlay health, and how.
CustomHealthAPI.Enums.OverlayFlags = {
	REVERSE_ORDER = 1 << 0,  -- Overlay from Left-to-Right instead of the default Right-to-Left
	FILLED_CONTAINER = 1 << 1,  -- Regular heart containers filled with any red health
	EMPTY_CONTAINER = 1 << 2,  -- Regular empty heart containers
	FILLED_BONE = 1 << 3,  -- Heart containers with innate HP (ie, bone hearts) that are currently filled with any red health
	EMPTY_BONE = 1 << 4,  -- Empty heart containers with innate HP (ie, bone hearts)
	SOUL = 1 << 5,  -- Soul health
	BROKEN = 1 << 6,  -- Broken hearts (containers that cannot hold any health)
}
-- Composite flags
CustomHealthAPI.Enums.OverlayFlags.RED  = CustomHealthAPI.Enums.OverlayFlags.FILLED_CONTAINER | CustomHealthAPI.Enums.OverlayFlags.FILLED_BONE
CustomHealthAPI.Enums.OverlayFlags.ANY_HP = CustomHealthAPI.Enums.OverlayFlags.RED | CustomHealthAPI.Enums.OverlayFlags.SOUL | CustomHealthAPI.Enums.OverlayFlags.EMPTY_BONE
CustomHealthAPI.Enums.OverlayFlags.CONTAINER = CustomHealthAPI.Enums.OverlayFlags.FILLED_CONTAINER | CustomHealthAPI.Enums.OverlayFlags.EMPTY_CONTAINER
CustomHealthAPI.Enums.OverlayFlags.BONE = CustomHealthAPI.Enums.OverlayFlags.FILLED_BONE | CustomHealthAPI.Enums.OverlayFlags.EMPTY_BONE
CustomHealthAPI.Enums.OverlayFlags.ANY_CONTAINER = CustomHealthAPI.Enums.OverlayFlags.CONTAINER | CustomHealthAPI.Enums.OverlayFlags.BONE
CustomHealthAPI.Enums.OverlayFlags.NONBROKEN = CustomHealthAPI.Enums.OverlayFlags.ANY_HP | CustomHealthAPI.Enums.OverlayFlags.ANY_CONTAINER
CustomHealthAPI.Enums.OverlayFlags.ALL = CustomHealthAPI.Enums.OverlayFlags.NONBROKEN | CustomHealthAPI.Enums.OverlayFlags.BROKEN

-- Preset flag sets used by the vanilla overlays
CustomHealthAPI.Enums.OverlayFlagSets = {
	GOLDEN = { CustomHealthAPI.Enums.OverlayFlags.ANY_HP },
	ETERNAL = {
		CustomHealthAPI.Enums.OverlayFlags.RED | CustomHealthAPI.Enums.OverlayFlags.EMPTY_CONTAINER,
		CustomHealthAPI.Enums.OverlayFlags.ALL | CustomHealthAPI.Enums.OverlayFlags.REVERSE_ORDER,
	},
}

CustomHealthAPI.Enums.OverlayMode = {
	NORMAL = 0,  -- Standard overlay behaviour - overlays fill overtop hearts end to end and can move if the size of the health bar changes.
	STICKY_STRICT = 1,  -- Once overlayed on a heart, stay overlayed on THAT specific heart only, until it is removed or becomes ineligible for overlaying.
	STICKY_LITE = 2,  -- Like sticky, but if the overlayed heart is removed, tries to move to another nearby heart if possible.
}

CustomHealthAPI.Enums.HealthKinds = {
	NONE = -1,
	HEART = 0,
	COIN = 1,
}

CustomHealthAPI.Enums.Callbacks = {
	ON_SAVE = "CHAPI_ON_SAVE",
	ON_LOAD = "CHAPI_ON_LOAD",
	PRE_ADD_HEALTH = "CHAPI_PRE_ADD_HEALTH",
	POST_RENDER_HP_BAR = "CHAPI_POST_RENDER_HP_BAR",
	PRE_RENDER_HOLY_MANTLE = "CHAPI_PRE_RENDER_HOLY_MANTLE",
	POST_HEALTH_DAMAGED = "CHAPI_POST_HEALTH_DAMAGED",
	PRE_PLAYER_DAMAGE = "CHAPI_PRE_PLAYER_DAMAGE",
	POST_PLAYER_DAMAGE = "CHAPI_POST_PLAYER_DAMAGE",
	POST_PLAYER_GENESIS = "CHAPI_POST_PLAYER_GENESIS",
	POST_GENESIS = "CHAPI_POST_GENESIS",
	PRE_ETERNAL_HEAL = "CHAPI_PRE_ETERNAL_HEAL",
	PRE_SPIRIT_SHACKLES_HEAL = "CHAPI_PRE_SPIRIT_SHACKLES_HEAL",
	PRE_RENDER_UNKNOWN_CURSE = "CHAPI_PRE_RENDER_UNKNOWN_CURSE",
	CAN_PICK_HEALTH = "CHAPI_CAN_PICK_HEALTH",
	POST_RESYNC_PLAYER = "CHAPI_POST_RESYNC_PLAYER",
	POST_PLAYER_INITIALIZE = "CHAPI_POST_PLAYER_INITIALIZE",
	POST_PLAYER_REVIVED = "CHAPI_POST_PLAYER_REVIVED",
	GET_MAX_HP_CONVERSION = "CHAPI_GET_MAX_HP_CONVERSION",
	PRE_HEALTH_DAMAGED = "CHAPI_PRE_HEALTH_DAMAGED",
	PRE_BLOOD_OATH_DAMAGE = "CHAPI_PRE_BLOOD_OATH_DAMAGE",
	PRE_GLASS_CANNON_HEAL = "CHAPI_PRE_GLASS_CANNON_HEAL",
	PRE_NOKILL_HEAL = "CHAPI_PRE_NOKILL_HEAL",
	POST_CHANGE_PLAYER_TYPE = "CHAPI_POST_CHANGE_PLAYER_TYPE",
	PRE_SUMPTORIUM_CLOT_SELECT = "CHAPI_PRE_SUMPTORIUM_CLOT_SELECT",
	PRE_SUMPTORIUM_CLOT_INIT = "CHAPI_PRE_SUMPTORIUM_CLOT_INIT",
	POST_SUMPTORIUM_CLOT_INIT = "CHAPI_POST_SUMPTORIUM_CLOT_INIT",
	PRE_SUMPTORIUM_CLOT_ABSORB = "CHAPI_PRE_SUMPTORIUM_CLOT_ABSORB",
	POST_SUMPTORIUM_CLOT_ABSORB = "CHAPI_POST_SUMPTORIUM_CLOT_ABSORB",
	POST_ADD_HEALTH = "CHAPI_POST_ADD_HEALTH",
	POST_RENDER_HOLY_MANTLE = "CHAPI_POST_RENDER_HOLY_MANTLE",
	POST_RENDER_UNKNOWN_CURSE = "CHAPI_POST_RENDER_UNKNOWN_CURSE",
	POST_UPDATE_HEALTH_STATE = "CHAPI_POST_UPDATE_HEALTH_STATE",
	PRE_HEARTBREAK_HEAL = "CHAPI_PRE_HEARTBREAK_HEAL",
	GET_MAX_HP_CAP = "CHAPI_GET_MAX_HP_CAP",
	PRE_RENDER_LIVES = "CHAPI_PRE_RENDER_LIVES",
	POST_RENDER_LIVES = "CHAPI_POST_RENDER_LIVES",
	PRE_RENDER_HEARTS = "CHAPI_PRE_RENDER_HEARTS",
	POST_RENDER_HEARTS = "CHAPI_POST_RENDER_HEARTS",
	PRE_RENDER_HP_BAR = "CHAPI_PRE_RENDER_HP_BAR",
	POST_OVERLAY_BROKEN = "CHAPI_POST_OVERLAY_BROKEN",
	POST_RESET_HOLY_MANTLES = "CHAPI_POST_RESET_HOLY_MANTLES",
	PRE_HEALTH_RENDER = "CHAPI_PRE_HEALTH_RENDER",
	POST_HEALTH_RENDER = "CHAPI_POST_HEALTH_RENDER",
	PRE_AFTER_HEALTH_ICON_RENDER = "CHAPI_PRE_AFTER_HEALTH_ICON_RENDER",
	POST_AFTER_HEALTH_ICON_RENDER = "CHAPI_POST_AFTER_HEALTH_ICON_RENDER",
	PRE_BELOW_HEALTH_ICON_RENDER = "CHAPI_PRE_BELOW_HEALTH_ICON_RENDER",
	POST_BELOW_HEALTH_ICON_RENDER = "CHAPI_POST_BELOW_HEALTH_ICON_RENDER",
	PRE_CHECK_SWAP_TWIN_RENDERING = "CHAPI_PRE_CHECK_SWAP_TWIN_RENDERING",
	POST_LOAD_HEALTH_FROM_BACKUP = "CHAPI_POST_LOAD_HEALTH_FROM_BACKUP",
	PRE_YUM_HEART_HEAL = "CHAPI_PRE_YUM_HEART_HEAL",
	POST_YUM_HEART_HEAL = "CHAPI_POST_YUM_HEART_HEAL",
	GET_ALABASTER_BOX_OWNER = "CHAPI_GET_ALABASTER_BOX_OWNER",
	PRE_SYNC_GULLET_HEARTS = "CHAPI_PRE_SYNC_GULLET_HEARTS",
	POST_SYNC_GULLET_HEARTS = "CHAPI_POST_SYNC_GULLET_HEARTS",
	GET_GULLET_HEART_KEY = "CHAPI_GET_GULLET_HEART_KEY",
	SHOULD_RENDER_BELOW_HEALTH_ICON = "CHAPI_SHOULD_RENDER_BELOW_HEALTH_ICON",
	
	-- OLD CALLBACKS IDS THAT REDIRECT TO MODERN CALLBACKS
	-- AVOID USING THESE
	PRE_RENDER_HEART = 4, -- PRE_HEALTH_RENDER
	POST_RENDER_HEART = 31, -- POST_HEALTH_RENDER
}
CustomHealthAPI.Enums.RunCallbackFuncs = {}

CustomHealthAPI.Enums.CallbacksOldToNew = { -- for backwards compatibility purposes, don't bother adding to this list
	[1] = "CHAPI_ON_SAVE",
	[2] = "CHAPI_ON_LOAD",
	[3] = "CHAPI_PRE_ADD_HEALTH",
	[5] = "CHAPI_POST_RENDER_HP_BAR",
	[6] = "CHAPI_PRE_RENDER_HOLY_MANTLE",
	[7] = "CHAPI_POST_HEALTH_DAMAGED",
	[8] = "CHAPI_PRE_PLAYER_DAMAGE",
	[9] = "CHAPI_POST_PLAYER_DAMAGE",
	[10] = "CHAPI_POST_PLAYER_GENESIS",
	[11] = "CHAPI_POST_GENESIS",
	[12] = "CHAPI_PRE_ETERNAL_HEAL",
	[13] = "CHAPI_PRE_SPIRIT_SHACKLES_HEAL",
	[14] = "CHAPI_PRE_RENDER_UNKNOWN_CURSE",
	[15] = "CHAPI_CAN_PICK_HEALTH",
	[16] = "CHAPI_POST_RESYNC_PLAYER",
	[17] = "CHAPI_POST_PLAYER_INITIALIZE",
	[18] = "CHAPI_POST_PLAYER_REVIVED",
	[19] = "CHAPI_GET_MAX_HP_CONVERSION",
	[20] = "CHAPI_PRE_HEALTH_DAMAGED",
	[21] = "CHAPI_PRE_BLOOD_OATH_DAMAGE",
	[22] = "CHAPI_PRE_GLASS_CANNON_HEAL",
	[23] = "CHAPI_PRE_NOKILL_HEAL",
	[24] = "CHAPI_POST_CHANGE_PLAYER_TYPE",
	[25] = "CHAPI_PRE_SUMPTORIUM_CLOT_SELECT",
	[26] = "CHAPI_PRE_SUMPTORIUM_CLOT_INIT",
	[27] = "CHAPI_POST_SUMPTORIUM_CLOT_INIT",
	[28] = "CHAPI_PRE_SUMPTORIUM_CLOT_ABSORB",
	[29] = "CHAPI_POST_SUMPTORIUM_CLOT_ABSORB",
	[30] = "CHAPI_POST_ADD_HEALTH",
	[32] = "CHAPI_POST_RENDER_HOLY_MANTLE",
	[33] = "CHAPI_POST_RENDER_UNKNOWN_CURSE",
	[34] = "CHAPI_POST_UPDATE_HEALTH_STATE",
	[35] = "CHAPI_PRE_HEARTBREAK_HEAL",
	[36] = "CHAPI_GET_MAX_HP_CAP",
	[37] = "CHAPI_PRE_RENDER_LIVES",
	[38] = "CHAPI_POST_RENDER_LIVES",
	[40] = "CHAPI_PRE_RENDER_HEARTS",
	[41] = "CHAPI_POST_RENDER_HEARTS",
	[42] = "CHAPI_PRE_RENDER_HP_BAR",
	[43] = "CHAPI_POST_OVERLAY_BROKEN",
	[44] = "CHAPI_POST_RESET_HOLY_MANTLES",
	[45] = "CHAPI_PRE_HEALTH_RENDER",
	[46] = "CHAPI_POST_HEALTH_RENDER",
	[47] = "CHAPI_PRE_AFTER_HEALTH_ICON_RENDER",
	[48] = "CHAPI_POST_AFTER_HEALTH_ICON_RENDER",
	[49] = "CHAPI_PRE_BELOW_HEALTH_ICON_RENDER",
	[50] = "CHAPI_POST_BELOW_HEALTH_ICON_RENDER",
	[51] = "CHAPI_PRE_CHECK_SWAP_TWIN_RENDERING",
	[52] = "CHAPI_POST_LOAD_HEALTH_FROM_BACKUP",
	[53] = "CHAPI_PRE_YUM_HEART_HEAL",
	[54] = "CHAPI_POST_YUM_HEART_HEAL",
	[55] = "CHAPI_GET_ALABASTER_BOX_OWNER",
}

CustomHealthAPI.Enums.PlayerSlot = {
	STRAWMAN = -1,
	PLAYER_ONE = 0,
	PLAYER_TWO = 1,
	PLAYER_THREE = 2,
	PLAYER_FOUR = 3,
	ESAU = 4,
	PLAYER_ONE_ESAU = 4,
	PLAYER_TWO_ESAU = 5,
	PLAYER_THREE_ESAU = 6,
	PLAYER_FOUR_ESAU = 7,
}

CustomHealthAPI.Enums.CallbackPriorities = {
	FIRST = math.mininteger,
	EARLY = -920,
	LATE = 920,
	LAST = math.huge,
}

CustomHealthAPI.Enums.MantleType = {
	UNKNOWN = -2,
	NONE = -1,
	HOLY = 0,
	WOODEN_CROSS = 1,
	BLANKET = 2,
	HOLY_CARD = 3,
}
